### ISSUE TITLE
Fix script does not work

### ISSUE THREAD

**Issue by fl0r3ntl1onn3t** [simonkrenger/apple-health-to-fitbit#12]
Hi Simon,

I gave it a try but maybe I did something wrong.
I launched your script fore the first step. It asked me to run the fix script. But nothing happened then

Here are 2 screenshot and I do not succeed in going further.

Can you help?

Regards.
 
![Capture d’écran 2023-01-06 à 15 08 03](https://user-images.githubusercontent.com/122103553/211029101-344ee810-66ea-4430-9b4f-26a3c7a1f9ba.png)
![Capture d’écran 2023-01-06 à 15 08 09](https://user-images.githubusercontent.com/122103553/211029116-89916e77-b687-4011-862f-8329be650d75.png)

**Comment by simonkrenger** [comment]
Thanks for opening this issue.

>  I launched your script fore the first step. It asked me to run the fix script. But nothing happened then

From the screenshots, it really seems that your "export_cda.xml".
How long did you wait for the `fix_invalid_export_cda_xml.py` to run?
How large is your XML file, as it may take a long time to go through the file to fix it?

Maybe we'll need to check your "export_cda.xml" file further to see what is wrong with it.

**Comment by simonkrenger** [comment]
@fl0r3ntl1onn3t Yes, especially when the file is large (>1GB), I would propose that you wait some time to see if it finishes. There seems to be a lot of data in your file, which takes time to go through. The code is not particularly well optimised, so it may take some time.

For the moment I am closing this issue, however feel free to reopen it if you still see problems.
