### ISSUE TITLE
Swim distance

### ISSUE THREAD

**Issue by tanykim** [simonkrenger/apple-health-to-fitbit#13]
Hello! I just ran your code and I found one bug. In `HKQuantityTypeIdentifierDistanceSwimming.csv` the value column has the pool length, not actual swim distance. 

Can you take a look at that when you have a chance? Thank you so much.

**Comment by tanykim** [comment]
Looking into the xml file from Apple, it seems way much complicated than I thought - thanks!

**Comment by simonkrenger** [comment]
Thanks @tanykim for your feedback.
If you are seeing any other issues, feel free to open another issue
