### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by gjones75** [simonkrenger/apple-health-to-fitbit#16]
Hello! 

Excited to find this script but it hasn't worked for me thus far. I get the following :

guyjones@Guys-MBP-3 ~ % python3 /Users/guyjones/Desktop/apple_health_export_2/export.xml
  File "/Users/guyjones/Desktop/apple_health_export_2/export.xml", line 1
    <?xml version="1.0" encoding="UTF-8"?>
    ^
SyntaxError: invalid syntax

Can you help me please? Desperate to sync my health data to Garmin Connect!

Thank you!

**Comment by simonkrenger** [comment]
Hi @gjones75 It seems your "export.xml" file has some unexpected content.
Can you provide the output for the command `head export.xml` in your folder? I'd like to check what content your "export.xml" has at the very beginning of the document.

**Comment by gjones75** [comment]
Hi @simonkrenger my apologies for the delay, I have been on holiday. I'm no expert in these things but is this what you wanted to see? 

?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE HealthData [

<!ELEMENT HealthData (ExportDate,Me,(Record|Correlation|Workout|ActivitySummary|ClinicalRecord|Audiogram|VisionPrescription)*)>
<!ATTLIST HealthData
  locale CDATA #REQUIRED
>
<!ELEMENT ExportDate EMPTY>
<!ATTLIST ExportDate
  value CDATA #REQUIRED

**Comment by gjones75** [comment]
I'm not sure it's displaying properly here so I will try to attach a text file
[head.docx](https://github.com/user-attachments/files/16558104/head.docx)

**Comment by simonkrenger** [comment]
Thanks @gjones75 for uploading that. It seems your file starts like this:

```
?xml version="1.0" encoding="UTF-8"?>
``` 

But it should look like this (notice the additional "<" at the start of the line):

```
<?xml version="1.0" encoding="UTF-8"?>
```

Can you edit the `export.xml` file, add the missing character, then save the file and try the script again? Let me know if that helps

**Comment by gjones75** [comment]
@simonkrenger  I checked the file and the "<" is there. I must have missed it off when copying the text from terminal, sorry.
This is the complete first line  
[head first line.docx](https://github.com/user-attachments/files/16561709/head.first.line.docx)

**Comment by simonkrenger** [comment]
@gjones75 Ah! Re-reading your initial issue I think I know what went wrong :-) You ran the following command:

```
guyjones@Guys-MBP-3 ~ % python3 /Users/guyjones/Desktop/apple_health_export_2/export.xml
```

This is the wrong command, as you executed `python3` with the XML file. Please do the following on your command line:

```
cd /Users/guyjones/Desktop/apple_health_export_2/
python3 health_to_fitbit.py
```

This will change into the directory downloaded from the repository and then executes the Python script to convert your file. Note that I am executing the Python scripts from this repository, not the XML file. You can alternatively run the Python script by executing the following two commands:

```
cd /Users/guyjones/Desktop/apple_health_export_2/
./health_to_fitbit.py
```

You may need to run `./fix_invalid_export_cda_xml.py` if the script tells you to. Let me know if that works.

**Comment by gjones75** [comment]
Thanks for looking again. I get this now

***@***.*** apple_health_export_2 % ./health_to_fitbit.py

./health_to_fitbit.py: line 7: syntax error near unexpected token `newline'

./health_to_fitbit.py: line 7: `<!DOCTYPE html>'

**Comment by simonkrenger** [comment]
@gjones75 It seems you have a HTML page saved as `health_to_fitbit.py` instead of just the content of the script.

Here are some more detailed instructions on how to start from scratch:

1. Download the script by going here: https://github.com/simonkrenger/apple-health-to-fitbit then click the green button "Code" on the top right, then "Download ZIP".
2. The ZIP file should now be downloaded. Move the downloaded file to the Desktop or somewhere else
3. Extract the files like you did before by double-clicking on the file
4. You should see multiple files being extracted into a new folder
5. Copy your `export.xml` and `export_cda.xml` files into the folder where you just extracted the scripts to. The scripts and the XML files need to be in the same folder.
6. Then use `cd` to move into the newly created folder (as you did above, but use the new path) and the command above again to run the script.

Let me know if that helps.

**Comment by gjones75** [comment]
@simonkrenger  Thank you so much. I do appreciate your patience with my ineptitude and the fact that this isn't an 'issue' with the script but with the user. I couldn't find that file and thought I'd downloaded it again but must have done it wrong. This has now worked although, despite the export containing all my data (weight, bmi, sleep, etc etc), all that has been converted into csv files is step data for each year, noting else. Is that what I should expect? I was hoping for more data to transfer.

**Comment by simonkrenger** [comment]
@gjones75 Glad to hear that this worked now.

> This has now worked although, despite the export containing all my data (weight, bmi, sleep, etc etc), all that has been converted into csv files is step data for each year, noting else. Is that what I should expect? I was hoping for more data to transfer.

The main issue is that there is very limited data that Garmin allows to be imported via CSV files: https://support.garmin.com/en-US/?faq=HfJ4xPchdD3cmZ2qtDpOR8

The script here extracts the fields weight, BMI, steps, distance and floors from the Apple Health data. For other data (sleep data for example) there is no way to import that into Garmin Connect via files as far as I understand. Activity data can be imported separately via .tcx, .fit or .gpx files.

I guess you could import them via a more elaborate integration into the Garmin Connect API, but that is a lot more involved and not the goal of these scripts at this time.

**Comment by gjones75** [comment]
@simonkrenger thank you for your explanation. I'm not complaining, was just hoping for more. I got steps only, not weight, mmi, distance or floors for some reason. They do seem to be in the export files though. It's not a huge deal, just wanted as much data transferred over to Garmin as possible. Thanks for your time.

**Comment by simonkrenger** [comment]
You're welcome. I definitely agree it would certainly be nice to ideally have all the Apple Health data in Garmin Connect. At least the other way around (Garmin Connect -> Apple Health) works fine-ish.

I am closing this issue, thanks for your patience.
