### ISSUE TITLE
Great Piece of Code -- Another Little Bug

### ISSUE THREAD

**Issue by DaCdnGuy** [simonkrenger/apple-health-to-fitbit#9]
Similar to your bug of Nov 30, 2020 - I needed to make the same float() change to lines 78 to 81 for the "steps_dict" as well as 90-93 for "floors_dict".  Int also needs to be added "distance_dict".

Looks like my steps and floors were pulled in after the changes.  However, noticed distance was not in the CSV - the revised INT tweak corrected the later.

Super Happy!

**Comment by simonkrenger** [comment]
@DaCdnGuy Thanks a lot for your input. I have incorporated your feedback in #10.

Could you let me know what changes you made to `distance_dict` so I can also incorporate these changes? An example would be great. Thanks!

**Comment by DaCdnGuy** [comment]
> 

I found the format for all three sections needed to include int and float.  Dist_dict ran without error with int being excluded, however, it didn't populate the table with data.  The tweak Although look like you found a much more elegant way to play with the combo.  I have included the revised py code as well as one cut of my data before and after the tweak to Dist_dict.    

I had about 7 years of data in Health and

 your code worked like a charm to pull it out.  I also liked your convert_export-xml_to_csv.py which I will be playing around with as time permits and see what other gems I can find in all the raw data it pulls out.   

[health_to_fitbit.zip](https://github.com/simonkrenger/apple-health-to-fitbit/files/7651967/health_to_fitbit.zip)
[fitbit_2020_v1.zip](https://github.com/simonkrenger/apple-health-to-fitbit/files/7651993/fitbit_2020_v1.zip)

**Comment by simonkrenger** [comment]
Great, thanks @DaCdnGuy I'll have a look at the code and your data to see if I can improve some of the code.

**Comment by simonkrenger** [comment]
@DaCdnGuy Could you clarify what you mean by "Dist_dict ran without error with int being excluded, however, it didn't populate the table with data."? Which table was not populated correctly? Did Garmin Connect not import the data correctly somehow?

If that is the case, I'll also parse the "Distance" values to `int`.

**Comment by simonkrenger** [comment]
Stale issue, closing it. Feel free to reopen it
